image: Visual Studio 2019

cache: '%LocalAppData%\NuGet\Cache'

build_script:
  - msbuild /t:Restore /t:Build /p:Configuration=Release

after_build:
  - dotnet pack --configuration release ValveResourceFormat\ValveResourceFormat.csproj
  - dotnet publish --configuration Release -p:PublishSingleFile=true --runtime win-x64 GUI\GUI.csproj
  - dotnet publish --configuration Release -p:PublishSingleFile=true --runtime win-x64 Decompiler\Decompiler.csproj
  - rmdir /S /Q Decompiler\obj
  - dotnet publish --configuration Release -p:PublishSingleFile=true --runtime linux-x64 Decompiler\Decompiler.csproj
  - rmdir /S /Q Decompiler\obj
  - dotnet publish --configuration Release -p:PublishSingleFile=true --runtime osx-x64 Decompiler\Decompiler.csproj

test_script:
- dotnet test

artifacts:
- path: Decompiler\bin\Release\win-x64\publish
  name: Decompiler-win-x64
- path: Decompiler\bin\Release\linux-x64\publish
  name: Decompiler-linux-x64
- path: Decompiler\bin\Release\osx-x64\publish
  name: Decompiler-osx-x64
- path: GUI\bin\Release\win-x64\publish
  name: GUI
- path: '**\*.nupkg'
  name: ValveResourceFormat

deploy:
- provider: GitHub
  auth_token:
    secure: hnDOlho1DI06VB/xFX6uvqoBUxo41/jV/186OLIMxOzFfsBaPoTavjVSqQdVrebT
  draft: false
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true
