name: Bug Report
description: File a bug report
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: input
  attributes:
    label: What Valve game does this happen in
    placeholder: "Dota 2"
  validations:
    required: true

- type: textarea
  attributes:
    label: Reference file in a Valve game
    description: Give a filename that causes this behavior.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: input
  attributes:
    label: What version of VRF are you using? On what platform?
    description: Before creating an issue, make sure it still exists on the latest unstable build.
  validations:
    required: true
